name: flutter_app_identity
description: Manage Flutter app identity (app names and bundle identifiers) for Android and iOS.
version: 0.1.4
homepage: https://github.com/genesisgamingllc/flutter_app_identity

topics:
  - flutter
  - android
  - ios
  - cli
  - tooling

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  path: ^1.9.0

executables:
  flutter_app_identity:
